[phases.setup]
nixPkgs = ["nodejs-20_x", "tesseract", "ffmpeg"]

[phases.build]
cmds = ["npm ci", "npx prisma generate", "npm run build", "mkdir -p uploads"]

[start]
cmd = "npx prisma migrate deploy && node dist/main"
